---
- name: Testing andrewrothstein.emacs
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'emacs --version'
      ansible.builtin.command: emacs --version
      changed_when: false
      register: emacs_test_output
    - name: Output of 'emacs --version'
      ansible.builtin.debug:
        msg: '{{ emacs_test_output.stdout }}'
